services:
  web:
    image: php:8.2-apache
    container_name: loja_magica_web
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: loja_magica_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loja_magica
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: loja_magica_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: